name: Update README

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api?username=whoiam1101&theme=vision-friendly-dark&show_icons=true&hide_border=true&count_private=true"
          curl -o README.md "https://github-readme-stats.vercel.app/api/top-langs/?username=whoiam1101&theme=vision-friendly-dark&show_icons=true&hide_border=true&layout=compact"
          curl -o README.md "https://streak-stats.demolab.com?user=whoiam1101&theme=vision-friendly-dark&hide_border=true"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Updated README"
          git push
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
